// src/pages/Cart/index.tsx
import React, { useContext } from 'react';
import { useHistory } from 'react-router-dom';

import { ResumeContext } from 'context/resume';

import { GlobalContainer } from 'styles/global';

import Header from 'components/Header';
import Products from 'components/Products';
import Price from 'components/Price';
import Button from 'components/Button';

const Cart: React.FC = () => {
  const history = useHistory();
  const { handleSetCartItems } = useContext(ResumeContext);

  const handleSubmit = () => {
    history.push('/payment');
  };

  return (
    <>
      <Header />
      <GlobalContainer>
        <Products />
        <Price />
        <form onSubmit={handleSubmit}>
          <Button type="submit">SEGUIR PARA O PAGAMENTO</Button>
        </form>
      </GlobalContainer>
    </>
  );
};

export default Cart;

// src/views/Cart.vue
<template>
  <div class="px-2">
    <Products />
    <Resume />
    <Button
      title="Seguir para o pagamento"
      @click="goNext"
    />
  </div>
</template>

<script>
import Products from '@/components/Products.vue';
import Resume from '@/components/Resume.vue';
import Button from '@/components/Button.vue';

export default {
  name: 'Cart',
  components: {
    Products,
    Resume,
    Button,
  },
  methods: {
    goNext() {
      this.$router.push('payment');
    },
  },
};
</script>
