// src/features/cart/Cart.jsx
import React from 'react'
import Container from '../../components/Container/Container'
import Button from '../../components/Button/Button'
import ProductList from '../../components/ProductList/ProductList'

const CartFeature = () => {
  return (
    <>
      <Container title="Produtos">
        <ProductList />
      </Container>
      <Button toPage="payment">seguir para pagamento</Button>
    </>
  )
}

export default CartFeature

// src/views/Cart.vue
<template>
  <div class="px-2">
    <Products />
    <Resume />
    <Button
      title="Seguir para o pagamento"
      @click="goNext"
    />
  </div>
</template>

<script>
import Products from '@/components/Products.vue';
import Resume from '@/components/Resume.vue';
import Button from '@/components/Button.vue';

export default {
  name: 'Cart',
  components: {
    Products,
    Resume,
    Button,
  },
  methods: {
    goNext() {
      this.$router.push('payment');
    },
  },
};
</script>
