// src/views/Success.vue
<template>
  <div class="px-2">
    <OrderConfirm />
    <Products />
    <Resume />
  </div>
</template>

<script>
import OrderConfirm from '@/components/OrderConfirm.vue';
import Products from '@/components/Products.vue';
import Resume from '@/components/Resume.vue';

export default {
  name: 'Success',
  components: {
    OrderConfirm,
    Products,
    Resume,
  },
};
</script>

// src/pages/Success.tsx
import React from 'react'

import ProductList from '@/components/products/ProductList'
import ResumeValues from '@/components/resume/ResumeValues'
import { useCart } from '@/contexts/cart'

function Success (): React.ReactElement | null {
  const { cart } = useCart()

  if (!cart) {
    return null
  }

  return (
    <>
      <ProductList />
      <ResumeValues />
    </>
  )
}

export default Success
