// src/components/Steps/Steps.tsx
/* eslint-disable jsx-a11y/anchor-is-valid */

import React from 'react';
import { useLocation, LinkProps } from 'react-router-dom'
import styled from 'styled-components';

export const StyledSteps = styled.nav`
  background-color: white;
  border-radius: 0 0 3px 3px;
  box-shadow: 1px 1px 5px 0 rgba(0,0,29,0.22);
  height: 40px;

  ol {
    align-items: center;
    display: flex;
    height: 100%;
    justify-content: space-around;
    margin: 0;
    padding: 0;
  }
`;

interface StyledStepProps {
  active?: boolean;
}

export const StyledStep = styled.li<StyledStepProps>`
  align-items: center;
  display: flex;
  flex: 0;
  height: 100%;
  list-style-type: none;

  a {
    align-items: center;
    color: ${({ active, theme }) => {
      return active ? theme.colors.primaryLight : theme.colors.gray;
    }};
    display: inline-flex;
    font-size: 13px;
    font-weight: 700;
    height: 100%;
    line-height: 16px;
    text-decoration: none;
    text-transform: uppercase;
  }
`;

interface StepProps extends LinkProps {}

const Step: React.FC<StepProps> = ({ children, to }) => {
  const router = useLocation();
  return (
    <StyledStep active={router.pathname === to}>
      <a>{children}</a>
    </StyledStep>
  );
};

const Steps: React.FC = () => {
  return (
    <StyledSteps>
      <ol>
        <Step to="/cart">Sacola</Step>
        <Step to="/payment">Pagamento</Step>
        <Step to="/success">Confirmação</Step>
      </ol>
    </StyledSteps>
  );
};

export default Steps;

// src/components/Steps.vue
<template>
  <section class="steps">
    <ul>
      <router-link 
        tag="li" 
        v-for="(item, key) in items" 
        :key="key" 
        :to="item.to"
      >
        {{ item.label }}
      </router-link>
    </ul>
  </section>
</template>

<script>
export default {
  name: 'steps',
  props: {
    items: {
      required: true,
      type: Array
    }
  }
}
</script>

<style scoped lang="stylus">
.steps 
  box-shadow: 1px 1px 5px 0 rgba(0,0,29,0.22);
  padding 15px 10px
  background #fff

ul 
  display flex
  list-style none
  margin 0
  padding 0
  justify-content space-around
  font-weight bold
  text-transform uppercase
  font-size 13px
  color #CCC

li.router-link-exact-active 
  color #FF7800
</style>
