// src/components/CartItem.vue
<template>
  <div class="cart-item">
    <img width="65px" height="65px" class="item-image" :src="item.imageObjects[0].small"/>
    <div class="info">
      <h4 class="item-name">{{ item.name }}</h4>
      <span class="item-price">{{ item.priceSpecification.price }}</span>
    </div>
  </div>
</template>

<script>
export default {
  name: 'cart-item',
  props: {
    item: Object
  },
  data() {
    return {
    }
  }
}
</script>

<style lang="stylus">
.cart-item 
  border: 1px solid #EEE;
  padding 12px 10px 14px 10px
  border-radius 3px
  display flex

.info 
  display flex
  flex-direction column

.item-image 
  margin-right 11px

.item-name 
  color #212122
  font-size 13px
  font-weight 400
  margin 0
  padding 0
  margin-bottom 15px

.item-price
  color: #212122
  font-size 14px
  font-weight bold
  align-self flex-end
</style>

// src/components/Cart/CartItem/CartItem.jsx
import React from 'react'

import jss from 'jss'
import preset from 'jss-preset-default'

jss.setup(preset())

const styles = {
  card: {
    display: 'flex',
    padding: [12, 5],
    borderRadius: 3,
    margin: { bottom: 15 },
    border: {
      width: 1,
      style: 'solid',
      color: '#EEE',
    },
    '&:last-child': {
      margin: { bottom: 0 },
    }
  },
  column: {
    flex: 'auto',
    padding: [0, 5],
  },
  thumb: {
    height: 65,
    width: 65,
  },
  productName: {
    display: 'block',
    lineHeight: '16px',
    fontSize: 13,
    color: '#212122',
    height: 32,
    overflow: 'hidden',
    margin: { bottom: 15 },
  },
  productPrice: {
    display: 'block',
    color: '#212122',
    lineHeight: '17px',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'right',
  },
}

const { classes } = jss.createStyleSheet(styles).attach()

const CartItem = ({
  name,
  thumb,
  price,
}) =>
  <div className={classes.card}>
    <div className={classes.column}>
      <img src={thumb} title={name} className={classes.thumb} />
    </div>
    <div className={classes.column}>
      <span className={classes.productName}>{name}</span>
      <span className={classes.productPrice}>R$ {price.toFixed(2).replace('.', ',')}</span>
    </div>
  </div>

export default CartItem
